version: "3.7"
# docker run -p 6333:6333 qdrant/qdrant
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always